"""CLI entrypoint for ai-dev."""

from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console
from rich.table import Table

from ai_dev_toolkit._version import __version__
from ai_dev_toolkit.core.config import EvaluatorConfig
from ai_dev_toolkit.core.dataset import evaluate_dataset
from ai_dev_toolkit.core.errors import AIDevToolkitError
from ai_dev_toolkit.core.evaluator import evaluate

app = typer.Typer(
    name="ai-dev",
    help="AI Dev Toolkit CLI for evaluating LLM, RAG, and AI agent outputs.",
    no_args_is_help=True,
)
console = Console()
error_console = Console(stderr=True)


def version_callback(value: bool) -> None:
    """Print version and exit."""
    if value:
        console.print(f"ai-dev-toolkit v{__version__}")
        raise typer.Exit()


@app.callback()
def main(
    version: Annotated[
        bool | None,
        typer.Option(
            "--version",
            "-v",
            help="Show version and exit.",
            callback=version_callback,
            is_eager=True,
        ),
    ] = None,
) -> None:
    """AI Dev Toolkit CLI."""


@app.command(name="version")
def version_cmd() -> None:
    """Show the toolkit version."""
    console.print(f"ai-dev-toolkit v{__version__}")


def _read_file_or_exit(file_path: Path, label: str) -> str:
    """Read file content or exit with a clear error."""
    try:
        return file_path.read_text(encoding="utf-8")
    except Exception as e:
        error_console.print(
            f"[bold red]Error reading {label} file '{file_path}':[/bold red] {e}"
        )
        raise typer.Exit(code=1) from e


@app.command(name="evaluate")
def evaluate_cmd(
    prompt: Annotated[
        str | None,
        typer.Option("--prompt", "-p", help="Prompt text given to the LLM."),
    ] = None,
    response: Annotated[
        str | None,
        typer.Option("--response", "-r", help="Response text generated by the LLM."),
    ] = None,
    context: Annotated[
        str | None,
        typer.Option(
            "--context",
            "-c",
            help="Reference context text for faithfulness evaluation.",
        ),
    ] = None,
    prompt_file: Annotated[
        Path | None,
        typer.Option("--prompt-file", help="Path to file containing prompt text."),
    ] = None,
    response_file: Annotated[
        Path | None,
        typer.Option("--response-file", help="Path to file containing response text."),
    ] = None,
    context_file: Annotated[
        Path | None,
        typer.Option("--context-file", help="Path to file containing context text."),
    ] = None,
    provider: Annotated[
        str | None,
        typer.Option("--provider", help="LLM judge provider ('gemini', 'fake')."),
    ] = None,
    model: Annotated[
        str | None,
        typer.Option("--model", "-m", help="Model name override for judge provider."),
    ] = None,
    json_output: Annotated[
        bool,
        typer.Option("--json", help="Output evaluation results as raw JSON."),
    ] = False,
    min_score: Annotated[
        float | None,
        typer.Option(
            "--min-score",
            min=0.0,
            max=1.0,
            help="Minimum overall score threshold (exits with code 1 if below).",
        ),
    ] = None,
    temperature: Annotated[
        float,
        typer.Option("--temperature", help="Sampling temperature for judge LLM."),
    ] = 0.0,
    show_reasoning: Annotated[
        bool,
        typer.Option("--reasoning", help="Display judge reasoning in output table."),
    ] = False,
) -> None:
    """Evaluate an LLM response against a prompt and optional context."""
    # Resolve prompt
    final_prompt = prompt
    if final_prompt is None and prompt_file is not None:
        final_prompt = _read_file_or_exit(prompt_file, "prompt")

    # Resolve response
    final_response = response
    if final_response is None and response_file is not None:
        final_response = _read_file_or_exit(response_file, "response")

    # Resolve context
    final_context = context
    if final_context is None and context_file is not None:
        final_context = _read_file_or_exit(context_file, "context")

    if not final_prompt or not final_prompt.strip():
        error_console.print(
            "[bold red]Error:[/bold red] Missing required prompt. "
            "Please provide --prompt or --prompt-file."
        )
        raise typer.Exit(code=1)

    if not final_response or not final_response.strip():
        error_console.print(
            "[bold red]Error:[/bold red] Missing required response. "
            "Please provide --response or --response-file."
        )
        raise typer.Exit(code=1)

    # Build config
    config_kwargs: dict[str, object] = {"temperature": temperature}
    if provider:
        config_kwargs["provider"] = provider
    if model:
        config_kwargs["model"] = model

    try:
        config = EvaluatorConfig(**config_kwargs)  # type: ignore[arg-type]
    except Exception as e:
        error_console.print(f"[bold red]Configuration error:[/bold red] {e}")
        raise typer.Exit(code=1) from e

    try:
        result = evaluate(
            prompt=final_prompt,
            response=final_response,
            context=final_context,
            config=config,
        )
    except AIDevToolkitError as e:
        error_console.print(f"[bold red]Evaluation failed:[/bold red] {e}")
        raise typer.Exit(code=1) from e
    except Exception as e:
        error_console.print(f"[bold red]Unexpected error:[/bold red] {e}")
        raise typer.Exit(code=1) from e

    if json_output:
        print(result.to_json(indent=2))
    else:
        _display_rich_results(result, show_reasoning=show_reasoning)

    # Check minimum score threshold
    if min_score is not None:
        if result.overall < min_score:
            if not json_output:
                error_console.print(
                    f"\n[bold red]Threshold check failed:[/bold red] "
                    f"Overall score {result.overall:.2f} is below "
                    f"minimum threshold {min_score:.2f}."
                )
            raise typer.Exit(code=1)


@app.command(name="dataset")
def dataset_cmd(
    input_file: Annotated[
        Path,
        typer.Argument(
            help="Path to dataset file (.jsonl, .json, or .csv).",
            exists=True,
            file_okay=True,
            dir_okay=False,
            readable=True,
        ),
    ],
    output_csv: Annotated[
        Path | None,
        typer.Option("--output-csv", "-o", help="Path to export results as CSV."),
    ] = None,
    report_html: Annotated[
        Path | None,
        typer.Option("--report-html", help="Path to export HTML benchmark report."),
    ] = None,
    report_md: Annotated[
        Path | None,
        typer.Option("--report-md", help="Path to export Markdown benchmark report."),
    ] = None,
    provider: Annotated[
        str | None,
        typer.Option(
            "--provider",
            help="Judge provider override ('gemini', 'openai', 'ollama', 'fake').",
        ),
    ] = None,
    model: Annotated[
        str | None,
        typer.Option("--model", "-m", help="Model name override for judge provider."),
    ] = None,
    min_score: Annotated[
        float | None,
        typer.Option(
            "--min-score",
            help="Fail with exit code 1 if mean overall score is below threshold.",
        ),
    ] = None,
    json_output: Annotated[
        bool,
        typer.Option("--json", help="Output aggregate results as JSON."),
    ] = False,
) -> None:
    """Evaluate a batch dataset (.jsonl, .json, .csv) and generate benchmark reports."""
    config = EvaluatorConfig.find_and_load()
    if provider:
        config.provider = provider
    if model:
        config.model = model

    try:
        dataset_result = evaluate_dataset(dataset=input_file, config=config)
    except Exception as e:
        error_console.print(f"[bold red]Dataset evaluation failed:[/bold red] {e}")
        raise typer.Exit(code=1) from e

    # Export outputs if requested
    if output_csv:
        dataset_result.to_csv(output_csv)
    if report_html:
        dataset_result.to_html(report_html)
    if report_md:
        dataset_result.to_markdown(report_md)

    if json_output:
        print(dataset_result.to_json(indent=2))
    else:
        sample_cnt = dataset_result.total_samples
        table = Table(
            title=f"Dataset Evaluation Summary ({sample_cnt} samples)",
            show_header=True,
            header_style="bold cyan",
            box=None,
        )
        table.add_column("Metric", style="bold", width=20)
        table.add_column("Mean", justify="right", width=10)
        table.add_column("Median", justify="right", width=10)
        table.add_column("Min", justify="right", width=8)
        table.add_column("Max", justify="right", width=8)
        table.add_column("Count", justify="right", width=8)

        for m_name, summary in dataset_result.summary.items():
            mean_pct = _format_pct(summary.mean)
            table.add_row(
                m_name.replace("_", " ").title(),
                mean_pct,
                f"{summary.median:.2f}",
                f"{summary.min:.2f}",
                f"{summary.max:.2f}",
                str(summary.count),
            )

        console.print()
        console.print(table)
        console.print()

    # Min score check on dataset overall mean
    if min_score is not None:
        overall_mean = (
            dataset_result.summary["overall"].mean
            if "overall" in dataset_result.summary
            else 0.0
        )
        if overall_mean < min_score:
            if not json_output:
                error_console.print(
                    f"[bold red]Threshold check failed:[/bold red] "
                    f"Mean overall score {overall_mean:.2f} is below "
                    f"minimum threshold {min_score:.2f}."
                )
            raise typer.Exit(code=1)


def _format_pct(score: float | None) -> str:
    """Format float score as percentage string."""
    if score is None:
        return "—"
    pct = round(score * 100)
    if score >= 0.8:
        return f"[bold green]{pct}%[/bold green]"
    elif score >= 0.5:
        return f"[bold yellow]{pct}%[/bold yellow]"
    return f"[bold red]{pct}%[/bold red]"


def _display_rich_results(result: object, show_reasoning: bool = False) -> None:
    """Print results in a clean formatted Rich table."""
    res = result.to_dict()

    table = Table(
        title="AI Dev Toolkit Evaluation",
        show_header=True,
        header_style="bold cyan",
        box=None,
        pad_edge=False,
    )
    table.add_column("Metric", style="bold", width=16)
    table.add_column("Score", justify="right", width=10)
    if show_reasoning:
        table.add_column("Reasoning", style="dim", overflow="fold")

    # Add metric rows
    reasoning_map = res.get("reasoning", {})

    rel_pct = _format_pct(res.get("relevance"))
    if show_reasoning:
        table.add_row("Relevance", rel_pct, reasoning_map.get("relevance", ""))
    else:
        table.add_row("Relevance", rel_pct)

    comp_pct = _format_pct(res.get("completeness"))
    if show_reasoning:
        table.add_row("Completeness", comp_pct, reasoning_map.get("completeness", ""))
    else:
        table.add_row("Completeness", comp_pct)

    if res.get("faithfulness") is not None:
        faith_pct = _format_pct(res.get("faithfulness"))
        if show_reasoning:
            table.add_row(
                "Faithfulness", faith_pct, reasoning_map.get("faithfulness", "")
            )
        else:
            table.add_row("Faithfulness", faith_pct)

    table.add_section()
    overall_pct = _format_pct(res.get("overall"))
    if show_reasoning:
        table.add_row("Overall", overall_pct, "")
    else:
        table.add_row("Overall", overall_pct)

    console.print()
    console.print(table)

    # Metadata footer
    meta = res.get("metadata", {})
    provider_info = meta.get("provider", "unknown")
    model_info = meta.get("model", "")
    latency_info = meta.get("latency_ms")

    footer_parts = [f"Provider: [bold]{provider_info}[/bold]"]
    if model_info:
        footer_parts.append(f"Model: {model_info}")
    if latency_info is not None:
        footer_parts.append(f"Latency: {latency_info}ms")

    console.print(f"[dim]{' | '.join(footer_parts)}[/dim]\n")


if __name__ == "__main__":
    app()
